### ISSUE TITLE
Less Aggressive Filtering List

### ISSUE THREAD

**Issue by mpaunovic** [xarantolus/filtrite#10]
I guess for Bromite Extended you are using Fanboy's Annoyance List. The problem with that list is that it's huge and tries to be cure for all, thus breaking some sites especially the social media content. Luckily there is an alternative you may be well aware of. It's the AdGuard Annoyances filter list:

https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_14_Annoyances/filter.txt

It's very well optimized and it works great with uBlock filters - Annoyances. Please consider replacing Fanboy's Annoyance List with the AdGuard's. Or better yet, if it's not too much trouble, create a new list as an option with this change as a less aggressive/safer approach.

Thank you very much for all the great work you've been doing, please keep it up!

**Comment by xarantolus** [comment]
Sounds good, didn't know about that list. I added the new list as `Bromite Extended (Soft)`.

Thanks for bringing this up, I actually have no idea about which blocklists work good/bad so this is very appreciated :)

**Comment by mpaunovic** [comment]
You, sir, are a gentleman and a scholar! :)

Thank you so much, I'm closing this because it's solved.
