### ISSUE TITLE
Google promotions showing

### ISSUE THREAD

**Issue by fraction1** [xarantolus/filtrite#21]
First, ty for all the effort.

I noticed that when i google for example: ted baker
Google promotions are still showing
I also tested at:
https://d3ward.github.io/toolz/adblock.html

It shows :  https://googleadservices.com is not blocked
(Amazon and pinterest aren't blocked either)
Could u please add these to your extended.dat?
In bromite (latest version from github) I'm using in the adblock settings: https://github.com/xarantolus/filtrite/releases/latest/download/bromite-extended.dat

Thanks again

**Comment by xarantolus** [comment]
These domains are apprently not used for ads or have other reasons for not being included in common filter lists, at least according to AdguardTeam/AdGuardSDNSFilter#1043, easylist/easylist#12678 and easylist/easylist#13926. 

See also d3ward/toolz#31, d3ward/toolz#38

**Comment by fraction1** [comment]
Thanks for the reply

It does disapear in top of the page,  but when you scroll down, google promotions still will be shown, only half way the page. 
(Userscripts on and off makes no difference)
Strange, isn't it

**Comment by xarantolus** [comment]
> but this one kills a few websites (can't scroll anymore)
Yes, this is an issue with some sites, but usually the adblock rules include scroll fixes that should also be included in the script. Can you send me some domains where this happens? It's likely that the generator doesn't know about all scroll fix mechanisms

**Comment by fraction1** [comment]
https://sochicken.nl/
https://www.dumpert.nl/

Maybe more but it don't have them right now

**Comment by xarantolus** [comment]
> https://sochicken.nl/

This list does not show up in the adblock rules used by the cosmetic scripts. This means that only general rules are injected there (e.g. blocking elements with the `id` `cookies` and similar), and on my device this seems to scroll just fine.

> [dumpert.nl](https://www.dumpert.nl/)

On this page the following CSS in injected by the script in addition to the general stuff:
```css
body div.fc-ab-root:not(#style_important) { display: none !important; }body { overflow: visible !important; }
```
Again, on my device this seems to work fine.

Maybe there's some other issue at play here? 🤔

**Comment by fraction1** [comment]
Forced stopped bromite, cleared cache etc
Removed al the user scripts downloaded and activated them again 
Looks like it it's fixed now :)

Thanx again for your quick replies!
