### ISSUE TITLE
Unable to build filterlists.

### ISSUE THREAD

**Issue by Shrnrand** [xarantolus/filtrite#27]
I am having these errors and warnings coming up whenever I try to build. 
![Screenshot 2024-02-18 084126](https://github.com/xarantolus/filtrite/assets/83822969/2802aa17-f24d-4a05-a4d3-ec394d028443)
Let me know what could be the issue.

**Comment by xarantolus** [comment]
The log at https://github.com/Shrnrand/filtrite/actions/runs/7949917551/job/21701624002 shows the actual error message. The tool doesn't work on filterlists itself, but rather on a file that contains links to filterlists. So in your case, you should put your rules into a separate file and supply the URL to that file in main-filter.txt
