### ISSUE TITLE
deprecated warnings ⚠️

### ISSUE THREAD

**Issue by RicoHeat** [xarantolus/filtrite#28]
![Screenshot_20240419_042729](https://github.com/xarantolus/filtrite/assets/41478458/30c50d79-dbc1-4f10-9060-8a737e541199)
As of 2 days ago 'Build filterlists' are not being generated.

**Comment by RicoHeat** [comment]
@xarantolus Any suggestions?

**Comment by xarantolus** [comment]
Hmm yeah, that's not ideal. I upgraded them in the latest commit https://github.com/xarantolus/filtrite/commit/cf1edf06cca967ff477cdc9e80a85f545e232719

**Comment by RicoHeat** [comment]
> Hmm yeah, that's not ideal. I upgraded them in the latest commit [cf1edf0](https://github.com/xarantolus/filtrite/commit/cf1edf06cca967ff477cdc9e80a85f545e232719). Thank you for pointing it out :)

I'm still unable to build..

**Comment by xarantolus** [comment]
> I'm still unable to build..

Looking at the output [here](https://github.com/RicoHeat/filtrite/actions/runs/8911168336/job/24471913875), it's because a filter list doesn't load:
> 2024/05/01 15:14:59 Error while generating filter for "lists/Browser.Custom.BL.HighSecurity.txt": downloading filter lists: unexpected status code 503
panic: error while walking: downloading filter lists: unexpected status code 503

This kind of thing probably shouldn't stop the entire generation process

**Comment by xarantolus** [comment]
When looking at the code again, I noticed that the generation process errors if the last filter list download fails; so this should be fixed now

**Comment by RicoHeat** [comment]
> When looking at the code again, I noticed that the generation process errors if the last filter list download fails; so this should be fixed now

All seems well now.. Thanks.. 👍

**Comment by RicoHeat** [comment]
Closed
